# Generated by Django 3.2.10 on 2022-01-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Selling_price', models.IntegerField()),
                ('Km_driven', models.IntegerField()),
                ('Fuel', models.CharField(max_length=20)),
                ('Seller_type', models.CharField(max_length=50)),
                ('Transmission', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('Mileage', models.CharField(max_length=50)),
                ('Engine', models.CharField(max_length=50)),
                ('Max_power', models.CharField(max_length=50)),
                ('Torque', models.CharField(max_length=50)),
                ('Seats', models.IntegerField()),
            ],
        ),
    ]
