# Generated by Django 3.2.10 on 2022-01-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
