# Generated by Django 3.2.10 on 2022-01-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carapp', '0002_delete_cardetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('fuel', models.CharField(max_length=20)),
                ('seller_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('max_power', models.CharField(max_length=50)),
                ('torque', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
